version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: ["pnpm", "run", "start"]
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
